version: "3.8"

services:

  proxy:
    build: ./proxy
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - pm-buli-network

  frontend1:
    image: nginx:1.23.0-alpine
    volumes:
      - "./frontend:/usr/share/nginx/html:ro"
    networks:
      - pm-buli-network

  frontend2:
    image: nginx:1.23.0-alpine
    volumes:
      - "./frontend:/usr/share/nginx/html:ro"
    networks:
      - pm-buli-network

  frontend3:
    image: nginx:1.23.0-alpine
    volumes:
      - "./frontend:/usr/share/nginx/html:ro"
    networks:
      - pm-buli-network

  backend:
    build: ./server
    networks:
      - pm-buli-network
    volumes:
      - "./server/db.json:/db.json:rw"

networks:
  pm-buli-network:

    ipam:
      driver: default
      config:
        - subnet: "192.168.239.0/24"
          gateway: "192.168.239.1"
